#!/usr/bin/env python3

""" fooo || Barr """
import random
wordbank = ["indentation", "spaces"]

tlgstudents= ["Aaron", "Andy", "Asif", "Brent", "Cedric",
 "Chris", "Cory", "Ebrima", "Franco", "Greg", "Hoon",
 "Joey", "Jordan", "JC", "LB", "Mabel", "Shon", "Pat", "Zach"]
#print(wordbank[0])
#print(tlgstudents[6])
wordbank.append(4)
print(wordbank)
num = int(input(f"input a number between 0 and 18:\n"))
#student_name = tlgstudents[1:num:2]
student_name = tlgstudents[num]
randomName = random.choice(tlgstudents)
print(f"this is a random name: {randomName}")
print(student_name)

